# Site Settings
locale                   : "en-US"
title                    : "sleeping, on the go"
title_separator          : "-"
name                     : "sleeping, on the go"
description              : "Personal website of Quang Chien."
logo                     : "/assets/images/blog-photo.JPG"
url                      : "https://chienlax.github.io"
baseurl                  : "/chien-lax"
repository               : "chienlax/chien-lax"
words_per_minute         : 150

# Site Author
author:
  name             : "Quang Chien"
  avatar           : "/assets/images/bio-photo.JPG"
  bio              : "wannabe researcher, i am trying my best tho."
  location         : "Ha Noi, Viet Nam"
  email            : "chienlax.work@gmail.com"
  github           : "chienlax"

# Reading Files
include:
  - _pages
exclude:
  - .claude
  - .history
  - docs
  - essay-1
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: false
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: none

# Outputting
permalink: /:categories/:title/
timezone: Asia/Ho_Chi_Minh

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
